### ISSUE TITLE
PHPUnit_Extensions_Database_DataSet_YamlDataSet getTable and formatting numbers

### ISSUE THREAD

**Issue by Trudko** [sebastianbergmann/dbunit#123]
I have fixture file

```
accounts:
  -
     creditor_account: x
     debitor_account: y
     amount: 5.00
```

but when I load it using:

```
$yamlDataset = new \PHPUnit_Extensions_Database_DataSet_YamlDataSet(
    $pathToFixture
);
return $yamlDataset->getTable($tableName);
```

my test fails because 5.00 gets formated to 5.
